# Configuração do Servidor
# ==============================================================================
quarkus.http.root-path=${QUARKUS_HTTP_ROOT_PATH:/api}

# ==============================================================================
# Azure Functions
# ==============================================================================
quarkus.azure-functions.app-name=functions-tc-postech
quarkus.azure-functions.region=brazilsouth
quarkus.azure-functions.resource-group=rg-fiap-postech
quarkus.azure-functions.function-name=avaliacao-feedback
quarkus.azure-functions.runtime.java-version=21
quarkus.azure-functions.deploy=true

# ==============================================================================
# Configuração do Banco de Dados PostgreSQL
# ==============================================================================
quarkus.datasource.db-kind=${QUARKUS_DATASOURCE_DB_KIND:postgresql}
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:postech}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:Fiap@2026}
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://db-postech.postgres.database.azure.com:5432/postgres}

# ==============================================================================
# Hibernate
# ==============================================================================
quarkus.hibernate-orm.database.generation=${QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION:update}
quarkus.hibernate-orm.log.sql=${QUARKUS_HIBERNATE_ORM_LOG_SQL:true}

# =========================
# MAILER
# =========================
quarkus.mailer.host=${EMAIL_HOST}
quarkus.mailer.port=${EMAIL_PORT}
quarkus.mailer.username=${EMAIL_USER}
quarkus.mailer.password=${EMAIL_PASS}
quarkus.mailer.from=${EMAIL_FROM}
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.auth=true
quarkus.mailer.mock=false

# =========================
# TEST PROFILE
# =========================
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb
%test.quarkus.mailer.mock=true
%test.quarkus.mailer.enabled=false

# =========================
# PACKAGE
# =========================
quarkus.package.type=fast-jar


